"""The MemoryStore Protocol. The default implementation is
``store_sqlite.SqliteMemoryStore``; alternate stores register via the
``veriloqua.memory_stores`` entry-point group."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from veriloqua.memory.records import MemoryEntry, RequestLogRecord


@runtime_checkable
class MemoryStore(Protocol):
    # --- reads ---
    def active_entries(self, src_lang: str, tgt_lang: str, scopes: list[str]) -> list[MemoryEntry]:
        """All active, live entries for the pair+scopes — the material the
        deterministic span-scan is built from."""
        ...

    def get(self, entry_id: int) -> MemoryEntry | None: ...

    def conflicts(self) -> list[dict]: ...

    def stats(self) -> dict: ...

    # --- writes ---
    def add_entry(self, entry: MemoryEntry) -> int: ...

    def supersede(self, old_id: int, new_entry: MemoryEntry) -> int: ...

    def soft_delete(self, entry_id: int) -> bool: ...

    def record_conflict(self, existing_id: int, proposed_accepted: str, note: str = "") -> int: ...

    def promote_scope(self, entry_id: int, scope: str) -> bool: ...

    # --- feedback / audit ---
    def record_application(self, entry_id: int, request_id: str, tier: str = "exact") -> None: ...

    def apply_signals(self, entry_id: int, positive: int = 0, negative: int = 0) -> None: ...

    def run_maintenance(self) -> dict: ...

    # --- request log (ring buffer) ---
    def log_request(self, record: RequestLogRecord) -> None: ...

    def load_request(self, request_id: str) -> RequestLogRecord | None: ...

    def purge_log(self) -> int: ...

    def close(self) -> None: ...
